In [1]:
import numpy as np

In [2]:
#concepts:
#create an array of odd numbers, 0 to 9
#creating coppies of arrays 
#reshapping arrays
#Vertically stacking arrays

In [3]:
print(np.__version__)

1.26.4


In [4]:
# create a range of integers in numpy
x = np.arange(10)
print(x)
for i in x:
    print('*'*i)

[0 1 2 3 4 5 6 7 8 9]

*
**
***
****
*****
******
*******
********
*********


In [5]:
#create an array of booleans using .full():

x = np.full((3,3,3), True, dtype = bool)
print(x)
print(np.full((9), True, dtype = bool).reshape(3,3))

# now using .ones():

y = np.ones((3,3), dtype = bool)
print(y, "this is y \n\n\n\n")
print(np.zeros((3,3), dtype = bool))

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] this is y 




[[False False False]
 [False False False]
 [False False False]]


In [6]:
# array of odd numbers: Exersise  3 and 5
x = np.arange(1, 10, 2)
print(x)

#also using a boolean map
x = np.arange(10)
print(x%2 == 1)
print(x[np.array([False, True, False, True, False, True,False, True,False, True])], "Boolean Maps Work!")
x = x[x%2 == 1]
print(x)




[1 3 5 7 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9] Boolean Maps Work!
[1 3 5 7 9]


In [7]:
# exercise 5, replacing values that meet a condition with another value

x = np.arange(10)
x[x%2 == 1] = 69 # basically, if odd, change value to 69
print(x)

[ 0 69  2 69  4 69  6 69  8 69]


In [8]:
# exercise 6, creating a copy

x = np.arange(10)

x_copy = x.copy()

x_copy[x_copy %2 == 1] = -1

print(x_copy, x, "original is preserved")

[ 0 -1  2 -1  4 -1  6 -1  8 -1] [0 1 2 3 4 5 6 7 8 9] original is preserved


In [9]:
# reshaping

x = np.arange(10)

x = x.reshape(2,5)
print(x)

y = np.arange(9)
print(y.reshape(3, -1)) # use -1 to auto decide number of columns 

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# stacking arrays vertically: exercise 8

a = np.arange(15).reshape(-1, 5)
b = np.repeat(1, 10).reshape(-1, 5) # force number of columns, number of rows flexible

x = np.vstack([a,b]) # stacking two same shapped arrays 
print(x)

#usefull in concatinating datasets

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]


In [11]:
# exercise 9: stack horizontally:

a = np.arange(12).reshape(2, -1)
b = np.repeat(1, 8).reshape(2, -1)

x = np.hstack([a,b])
print(x)

[[ 0  1  2  3  4  5  1  1  1  1]
 [ 6  7  8  9 10 11  1  1  1  1]]


In [12]:
# exercise 10:

a = np.array([1,2,3])
b = np.repeat(a, 3)
c = np.hstack([b,a,a,a])
print(c)

# better:
print(np.hstack([np.repeat(a, 3), np.tile(a, 3)]), "better way")


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3] better way


In [16]:
a = np.array([1,4,5,6,7])
b = np.array([4,7,1,2,3])
print(np.intersect1d(a,b), "intersection of a and b")


[1 4 7] intersection of a and b
