In [1]:
num1="1a34fd"

num2=int(num1,base=16)

print(num2)

1717501


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
print(a+2)

[3 4 5 6 7]


In [6]:
print(a*a)

[ 1  4  9 16 25]


In [13]:
b = np.array(range(1,6))
print(b*b)
print(type(b))
print(list(b))
print(b.dtype)

[ 1  4  9 16 25]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
int32


In [15]:
c = np.array([1,2,3,4,5,6.6], dtype = "int16")
print(c)

[1 2 3 4 5 6]


In [12]:
print(c.dtype)

float64


In [19]:
d = np.array([True, False, "14"])
print(d.dtype)

<U5


In [23]:
e = np.array([[[1,2,3]]])
print(e, e.shape)

[[[1 2 3]]] (1, 1, 3)


In [28]:
f = np.array(list("hello world"), )
print(f.itemsize)

4


# os and files

In [1]:
import os

In [19]:
print(type(os.getcwd()))
print(type(os.listdir()))
directory_list = os.getcwd().split("\\")
print(directory_list[:-1])
new_dir = r"\\".join(directory_list[:-1])
print(new_dir)

<class 'str'>
<class 'list'>
['C:', 'Users', 'gould', 'OneDrive', 'Desktop', 'College Classes', 'ENGR 1330 - Computational Thinking - Fall 2024']
C:\\Users\\gould\\OneDrive\\Desktop\\College Classes\\ENGR 1330 - Computational Thinking - Fall 2024


In [3]:
%pwd

'C:\\Users\\gould\\OneDrive\\Desktop\\College Classes\\ENGR 1330 - Computational Thinking - Fall 2024\\Coding'

In [20]:
os.listdir()

['.ipynb_checkpoints',
 'Day1.ipynb',
 'Exam 1 test.ipynb',
 'firstNoteBook.ipynb',
 'minimod.py',
 'Week 2 Day 3.ipynb',
 'Week 3 Day 1.ipynb',
 'Week 3 Day 2.ipynb',
 'week 4 day 1.ipynb',
 'Week 4 Day 2.ipynb',
 'Week 4 Day 3.ipynb',
 'Week 5 Day 2.ipynb',
 'Week 5 Day 3.ipynb',
 'Week 6 Day 1.ipynb',
 'Week 6 Day 2.ipynb',
 'Week 7 Day 2.ipynb',
 '__pycache__']

In [73]:
coolfile = open("coolfile.txt", "w+")

coolfile.write("this is some awesome stuff \n")


coolfile.close()

In [74]:
coolfile = open("coolfile.txt", "a+")
coolfile.write("this is some awesome stuff \n")
coolfile.seek(0)
whatsinside = coolfile.read()
coolfile.close()

In [75]:
print(whatsinside)

this is some awesome stuff 
this is some awesome stuff 



In [77]:
try:
    os.remove("coolfile.txt")
except:
    print("hmmmm, seems to be an error. You might have already deleted the file")
print("the dang thing gone!")

hmmmm, seems to be an error. You might have already deleted the file
the dang thing gone!
