## numpy arrays

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])


In [3]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
c=np.array([[8,3,0,7,2,1],[4,8,1,4,2,9]])
c

array([[8, 3, 0, 7, 2, 1],
       [4, 8, 1, 4, 2, 9]])

In [5]:
x=[[[1,2,3],[2,4,6]],[[1,2,3],[3,5,7]],[[1,3,4],[2,4,6]]]
d=np.array(x)
d

array([[[1, 2, 3],
        [2, 4, 6]],

       [[1, 2, 3],
        [3, 5, 7]],

       [[1, 3, 4],
        [2, 4, 6]]])

In [6]:
e=np.array([[1,2,3],[3,4,5]])
e

array([[1, 2, 3],
       [3, 4, 5]])

### Array indexing

In [14]:
d

array([[[1, 2, 3],
        [2, 4, 6]],

       [[1, 2, 3],
        [3, 5, 7]],

       [[1, 3, 4],
        [2, 4, 6]]])

In [16]:
d[1:2:1,0:1:2,1:3:1]

array([[[2, 3]]])

In [18]:
# display the first rows
d[:,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 3, 4]])

In [ ]:
#display the second columns
d[:,:,1]

In [ ]:
# display the second 2D plane 
d[1,:,:]

In [ ]:
#display the 1st and 2nd columns of the 2nd row of the 3rd 2D plane
d[2,1,0:2]

In [ ]:
d.shape

In [8]:
## if any array element in array d is greater than 4, replace that element with 40
print(d)
for i in range(d.shape[-3]):
    for j in range(d.shape[-2]):
        for k in range(d.shape[-1]):
            if d[i,j,k]>4:
                print ("d[{},{},{}]".format(i,j,k))
                d[i,j,k]=40
                
print("\nmodified d:\n\n",d)

[[[ 1  2  3]
  [ 2  4 40]]

 [[ 1  2  3]
  [ 3 40 40]]

 [[ 1  3  4]
  [ 2  4 40]]]
d[0,1,2]
d[1,1,1]
d[1,1,2]
d[2,1,2]

modified d:

 [[[ 1  2  3]
  [ 2  4 40]]

 [[ 1  2  3]
  [ 3 40 40]]

 [[ 1  3  4]
  [ 2  4 40]]]


### re-arranging array elements

In [9]:
c

array([[8, 3, 0, 7, 2, 1],
       [4, 8, 1, 4, 2, 9]])

In [10]:
c1=np.reshape(c,(3,4)) ## total elements in array c is 12
print("c: \n",c)
print("c1: \n",c1)

c: 
 [[8 3 0 7 2 1]
 [4 8 1 4 2 9]]
c1: 
 [[8 3 0 7]
 [2 1 4 8]
 [1 4 2 9]]


In [13]:
# 2D to 2D
c4=np.reshape(c,(12,1))  
c4

array([[8],
       [3],
       [0],
       [7],
       [2],
       [1],
       [4],
       [8],
       [1],
       [4],
       [2],
       [9]])

In [14]:
# convert from 2D to 1D
c2=np.reshape(c,(12))
c2

array([8, 3, 0, 7, 2, 1, 4, 8, 1, 4, 2, 9])

In [15]:
#convert from 2D to 3D
c3=np.reshape(c,(3,2,2,1))
c3

array([[[[8],
         [3]],

        [[0],
         [7]]],


       [[[2],
         [1]],

        [[4],
         [8]]],


       [[[1],
         [4]],

        [[2],
         [9]]]])

In [16]:
d

array([[[ 1,  2,  3],
        [ 2,  4, 40]],

       [[ 1,  2,  3],
        [ 3, 40, 40]],

       [[ 1,  3,  4],
        [ 2,  4, 40]]])

In [17]:
np.transpose(d)  ## convert the columns into rows and rows into columns

array([[[ 1,  1,  1],
        [ 2,  3,  2]],

       [[ 2,  2,  3],
        [ 4, 40,  4]],

       [[ 3,  3,  4],
        [40, 40, 40]]])

### math operations

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.average(b)

5.0

In [20]:
np.average(b[2,:])

8.0

In [21]:
d

array([[[ 1,  2,  3],
        [ 2,  4, 40]],

       [[ 1,  2,  3],
        [ 3, 40, 40]],

       [[ 1,  3,  4],
        [ 2,  4, 40]]])

In [22]:
np.sqrt(d)

array([[[1.        , 1.41421356, 1.73205081],
        [1.41421356, 2.        , 6.32455532]],

       [[1.        , 1.41421356, 1.73205081],
        [1.73205081, 6.32455532, 6.32455532]],

       [[1.        , 1.73205081, 2.        ],
        [1.41421356, 2.        , 6.32455532]]])

In [23]:
c

array([[8, 3, 0, 7, 2, 1],
       [4, 8, 1, 4, 2, 9]])

In [24]:
np.exp(c)

array([[2.98095799e+03, 2.00855369e+01, 1.00000000e+00, 1.09663316e+03,
        7.38905610e+00, 2.71828183e+00],
       [5.45981500e+01, 2.98095799e+03, 2.71828183e+00, 5.45981500e+01,
        7.38905610e+00, 8.10308393e+03]])

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
d

array([[[ 1,  2,  3],
        [ 2,  4, 40]],

       [[ 1,  2,  3],
        [ 3, 40, 40]],

       [[ 1,  3,  4],
        [ 2,  4, 40]]])

In [27]:
e

array([[1, 2, 3],
       [3, 4, 5]])

In [28]:
print(e+d)

[[[ 2  4  6]
  [ 5  8 45]]

 [[ 2  4  6]
  [ 6 44 45]]

 [[ 2  5  7]
  [ 5  8 45]]]


In [29]:
a

array([1, 2, 3])

In [30]:
a+d

array([[[ 2,  4,  6],
        [ 3,  6, 43]],

       [[ 2,  4,  6],
        [ 4, 42, 43]],

       [[ 2,  5,  7],
        [ 3,  6, 43]]])

In [31]:
c

array([[8, 3, 0, 7, 2, 1],
       [4, 8, 1, 4, 2, 9]])

In [32]:
e

array([[1, 2, 3],
       [3, 4, 5]])

In [33]:
c+e

ValueError: operands could not be broadcast together with shapes (2,6) (2,3) 

In [ ]:
a

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a*b

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [36]:
b*a

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [37]:
e*d

array([[[  1,   4,   9],
        [  6,  16, 200]],

       [[  1,   4,   9],
        [  9, 160, 200]],

       [[  1,   6,  12],
        [  6,  16, 200]]])

In [38]:
b[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
e

array([[1, 2, 3],
       [3, 4, 5]])

In [40]:
e*b[0:2,:] # array multiplication on selective rows and/or columns

array([[ 1,  4,  9],
       [12, 20, 30]])

In [41]:
b[0:1,:]*d

array([[[  1,   4,   9],
        [  2,   8, 120]],

       [[  1,   4,   9],
        [  3,  80, 120]],

       [[  1,   6,  12],
        [  2,   8, 120]]])

In [42]:
b[0:2,:]*d

array([[[  1,   4,   9],
        [  8,  20, 240]],

       [[  1,   4,   9],
        [ 12, 200, 240]],

       [[  1,   6,  12],
        [  8,  20, 240]]])

### copying an array

In [43]:
a=np.array([1,2,3])
#b=np.array([1,2,3])
print(a)
acopy=np.copy(a)
a_dup=a
a[0]=5
print("a",a,"\nacopy",acopy,"\na_dup",a_dup) ## note the difference between creating copy of a and assigning a to another variable 

[1 2 3]
a [5 2 3] 
acopy [1 2 3] 
a_dup [5 2 3]


## sorting array elements

In [44]:
a = np.array([[17,-6,2],[86,-12,0],[0,23,12]])
print(a)
print()
print(np.sort(a))
print ("\nAlong columns : \n", np.sort(a,axis = 0)) #This will be sorting in each column
print ("\nAlong rows : \n", np.sort(a,axis = 1) ) #This will be sorting in each row
#print ("Sorting by default : \n", np.sort(a) )          #Same as above
print ("\nAlong None Axis : \n", np.sort(a,axis = None) ) #This will be sorted like a 1D array
#axis=2 for sortimg along height...

[[ 17  -6   2]
 [ 86 -12   0]
 [  0  23  12]]

[[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]

Along columns : 
 [[  0 -12   0]
 [ 17  -6   2]
 [ 86  23  12]]

Along rows : 
 [[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]

Along None Axis : 
 [-12  -6   0   0   2  12  17  23  86]


In [45]:
d

array([[[ 1,  2,  3],
        [ 2,  4, 40]],

       [[ 1,  2,  3],
        [ 3, 40, 40]],

       [[ 1,  3,  4],
        [ 2,  4, 40]]])

In [46]:
np.sort(d,axis=2)

array([[[ 1,  2,  3],
        [ 2,  4, 40]],

       [[ 1,  2,  3],
        [ 3, 40, 40]],

       [[ 1,  3,  4],
        [ 2,  4, 40]]])

    __________________________________________________________________________________________________
Practice:         


https://pythonexamples.org/numpy/#5    


http://54.243.252.9/engr-1330webroot/engr1330jb/_build/html/lessons/lesson09/lesson09.html  
    __________________________________________________________________________________________________
    