### Arrays:
--> Only consists of elements belonging to the same data type

--> Need to explicitly import a module for declaration

--> Can directly handle arithmetic operations

--> Preferred for longer sequence of data items

--> Comparatively more compact in memory size


In [1]:
import numpy as np

## numpy arrays

In [2]:
x=[[[1,2,3]]]
a=np.array(x,dtype="int16") # you can specify the type and size as int8, int32, int64, float8, float16, float32....etc
print(a)
#print(x)
type(a)

[[[1 2 3]]]


numpy.ndarray

In [3]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b1=np.array([[1.2,2,3],[4,5,6],[7,8,9]])
b1 # note ll numbers converted to float as one element was a float

array([[1.2, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [5]:
b1.dtype

dtype('float64')

In [6]:
b2=np.array([[1.2,2.5,3],[4,5.0,6],[7,8,9]],dtype="int16") # forcing all elements to become integers
b2 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [7]:
b3=np.array([[1,2,3],[4,5,6],[7,8,9]]) # mismatch in number of elements in the lists
b3 # you get an array of lists
#b3.ndim
#b3.dtype

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b4=np.array([[1,2,"a"],[4,5,6],[7,8,9]]) #what if you have a string?
b4  # all elements convetred to strings


array([['1', '2', 'a'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U11')

In [9]:
b5=np.array([[1,2,True],[4,5,6],[False,8,9]]) #what if you have bools?
b5

array([[1, 2, 1],
       [4, 5, 6],
       [0, 8, 9]])

In [10]:
b6=np.array([[1,2,True],[4,"h",6],[False,8,9]]) #what if you have bools strings and numbers?
b6

array([['1', '2', 'True'],
       ['4', 'h', '6'],
       ['False', '8', '9']], dtype='<U11')

In [11]:
c=np.array([[8,3,0,7,2,1],[4,8,1,4,2,9]])
c

array([[8, 3, 0, 7, 2, 1],
       [4, 8, 1, 4, 2, 9]])

In [12]:
e=[[[1,2,3]]]  # e is going to be a 2D array with dimensions (1,3) because of being enclosed by 2 pairs of brackets!
e=np.array(e)
e.shape
# try this too:
# e=[[[1,2,3]]] # its a 3D, with a shape (1,1,3)...

(1, 1, 3)

In [16]:
x=[[[1,2,3],[2,4,6]],[[1,2,3],[3,5,7]],[[1,3,4],[2,4,6]],[[1,3,5],[4,7,9]]]
d=np.array(x)
d

array([[[1, 2, 3],
        [2, 4, 6]],

       [[1, 2, 3],
        [3, 5, 7]],

       [[1, 3, 4],
        [2, 4, 6]],

       [[1, 3, 5],
        [4, 7, 9]]])

### array properties

In [17]:
q=d.shape
q## dimensions e.g. row,column
#type(d.shape) 
#q[2]

(4, 2, 3)

In [18]:
d.shape[-1]

3

In [19]:
b.dtype  ## data type of the elements

dtype('int32')

In [20]:
d.ndim  ## how many dimensions the array has

3

In [21]:
b.ndim

2

In [22]:
a.itemsize  ## size of each element in bytes

2

In [23]:
d.size  ## total number of elements in the array

24

In [24]:
d.nbytes ## total size of the array in bytes
print(d.nbytes)

96


### common numpy array generating functions

In [25]:
np.zeros(shape=(2,3,5,5)) #dimensions of the array depends on number of arguments
#4D in this example

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [26]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.identity(5)  ## generates a 2D identity array 
#also np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.linspace(1.5,20,50)   #1D array

array([ 1.5       ,  1.87755102,  2.25510204,  2.63265306,  3.01020408,
        3.3877551 ,  3.76530612,  4.14285714,  4.52040816,  4.89795918,
        5.2755102 ,  5.65306122,  6.03061224,  6.40816327,  6.78571429,
        7.16326531,  7.54081633,  7.91836735,  8.29591837,  8.67346939,
        9.05102041,  9.42857143,  9.80612245, 10.18367347, 10.56122449,
       10.93877551, 11.31632653, 11.69387755, 12.07142857, 12.44897959,
       12.82653061, 13.20408163, 13.58163265, 13.95918367, 14.33673469,
       14.71428571, 15.09183673, 15.46938776, 15.84693878, 16.2244898 ,
       16.60204082, 16.97959184, 17.35714286, 17.73469388, 18.1122449 ,
       18.48979592, 18.86734694, 19.24489796, 19.62244898, 20.        ])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.random.randint(2,12) ## generates a random number between 0 and 11

10

In [30]:
np.random.randint(1,7,size=100) #1D array

array([6, 4, 1, 3, 5, 6, 4, 4, 2, 5, 6, 5, 2, 6, 2, 5, 1, 6, 1, 6, 5, 6,
       4, 4, 5, 2, 2, 1, 4, 5, 3, 3, 1, 3, 6, 2, 3, 5, 6, 6, 5, 6, 3, 3,
       1, 1, 1, 1, 2, 3, 2, 4, 1, 4, 2, 4, 5, 4, 3, 1, 4, 5, 5, 1, 6, 3,
       3, 4, 3, 6, 5, 6, 1, 3, 3, 5, 6, 5, 5, 2, 4, 5, 1, 4, 3, 5, 5, 1,
       6, 4, 5, 4, 1, 4, 3, 3, 5, 3, 4, 5])

In [30]:
np.random.rand(2,3,4) # floating point values between 0 to 1
# argument sequence: (height,row,column)

array([[[0.52471978, 0.75820926, 0.63462368, 0.85784669],
        [0.75943359, 0.48610478, 0.41445653, 0.42133117],
        [0.34890228, 0.81062979, 0.3903606 , 0.75191898]],

       [[0.11666421, 0.70070399, 0.28498131, 0.7935743 ],
        [0.60970495, 0.58906337, 0.14552788, 0.43749393],
        [0.37316351, 0.45925822, 0.08044461, 0.1884848 ]]])

In [32]:
from numpy import random
random.rand(4,4,5)

array([[[0.79696646, 0.879094  , 0.205021  , 0.75161976, 0.75941261],
        [0.4513484 , 0.38163291, 0.56386214, 0.97467837, 0.90745078],
        [0.86100559, 0.70117397, 0.07577738, 0.36081316, 0.9889437 ],
        [0.8655858 , 0.50001089, 0.0256652 , 0.54002407, 0.87061736]],

       [[0.30398714, 0.65793315, 0.6091659 , 0.98871006, 0.59449095],
        [0.57064428, 0.32742071, 0.2822626 , 0.22891394, 0.25604025],
        [0.85071976, 0.26150206, 0.7105811 , 0.56424637, 0.58460093],
        [0.0085311 , 0.2619015 , 0.11788783, 0.68253136, 0.25136123]],

       [[0.36269252, 0.27416112, 0.10613291, 0.8896872 , 0.40637312],
        [0.57257637, 0.90868988, 0.35309428, 0.46647539, 0.13560229],
        [0.31608722, 0.83510319, 0.36578746, 0.71500413, 0.65401831],
        [0.45506873, 0.21208164, 0.37745994, 0.02982672, 0.52072612]],

       [[0.03184655, 0.38514768, 0.64736106, 0.90310877, 0.13874637],
        [0.08864126, 0.10868021, 0.60304195, 0.59571176, 0.01318065],
        [0.572